version: "2.0"

services:
  ff_client:
    container_name: ff-client
    expose:
      - 3000
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./ffClient/DockerFile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ".:/project/FF"
  ff_processor:
    container_name: ff-processor
    build:
      context: .
      dockerfile: ./ffProcessor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - ".:/project/FF"
  event-server:
    container_name: event-server
    build:
      context: .
      dockerfile: ./EventServer/DockerFile
    expose:
      - 4010
    ports:
      - 4010:4010
    depends_on:
      - validator
    volumes:
      - ".:/project/FF"
  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004
  identity-tp:
    image: hyperledger/sawtooth-identity-tp:1.0
    container_name: sawtooth-identity-tp-default
    depends_on:
      - validator
    entrypoint: identity-tp -vv -C tcp://validator:4004
  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - "4004:4004"
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
